### ISSUE TITLE
need an environment variable to start ssh or not

### ISSUE THREAD

**Issue by ict4ngo** [cloudbec/nuagebec-docker-ubuntu#1]
-e SSH_SERVER="true"

-e SSH_SERVER="false"

**Comment by mikefaille** [comment]
Ok.
Nice thing.

**Comment by mikefaille** [comment]
@ict4ngo 
I didn't test but it should be sharp.
2f40a85aa3cdf163411cb81e4435b2fb1036e425

**Comment by ict4ngo** [comment]
tested working as it should
